version: '3.0'

services:
  td1Node:
    image: node:alpine
    container_name: api-nodejs
    working_dir: /app/Order
    volumes:
      - ./app/Order:/app/Order
    ports:
      - "3000:3000"
    command: "npm run dev"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/sql:/docker-entrypoint-initdb.d


