version: '3.0'

services:
  td1Node:
    image: node:alpine
    container_name: api-nodejs
    working_dir: /app/Order
    volumes:
      - ./app/Order:/app/Order
    command: "npm run dev"
    env_file:
      - order.env
    depends_on:
      - db
    networks:
      - backend
    links:
      - db
  db:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    env_file:
      - order.env
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/sql:/docker-entrypoint-initdb.d
    networks:
      - backend
  auth:
    image: node:alpine
    container_name: auth-nodejs
    working_dir: /app/Auth
    volumes:
      - ./app/Auth:/app/Auth
    command: "npm run dev"
    env_file:
      - auth.env
    depends_on:
      - dbAuth
    networks:
      - backend
    links:
      - dbAuth
  dbAuth:
    image: mysql:5.7
    container_name: mysql-auth
    ports:
      - "3307:3306"
    env_file:
      - auth.env
    volumes:
      - ./db/data-auth:/var/lib/mysql
      - ./db/sql-auth:/docker-entrypoint-initdb.d
    networks:
      - backend
  gateway:
    image: node:alpine
    container_name: gateway-nodejs
    working_dir: /app/Gateway
    volumes:
      - ./app/Gateway:/app/Gateway
    ports:
      - "3000:3000"
    command: "npm run dev"
    env_file:
      - gateway.env
    networks:
      - backend
    links:
      - td1Node
      - auth
networks:
  backend:
    driver: bridge



