version: '3.0'

services:
  td1Node:
    image: node:alpine
    container_name: api-nodejs
    working_dir: /app/Order
    volumes:
      - ./app/Order:/app/Order
    ports:
      - "3000:3000"
    command: "npm run dev"
    env_file:
      - order.env
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    env_file:
      - order.env
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/sql:/docker-entrypoint-initdb.d
  auth:
    image: node:alpine
    container_name: auth-nodejs
    working_dir: /app/Auth
    volumes:
      - ./app/Auth:/app/Auth
    ports:
      - "3001:3001"
    command: "npm run dev"
    env_file:
      - auth.env
    depends_on:
      - dbAuth
  dbAuth:
    image: mysql:5.7
    container_name: mysql-auth
    ports:
      - "3307:3306"
    env_file:
      - auth.env
    volumes:
      - ./db/data-auth:/var/lib/mysql
      - ./db/sql-auth:/docker-entrypoint-initdb.d

